# Site settings
title: My Awesome Site
# email: youremail@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a sample description for my awesome site.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
# twitter_username: your_twitter_username
# github_username:  your_github_username

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Customization
# These settings allow you to customize your site's appearance and behavior.
# To override default settings, specify your custom values here.

# The theme's default layout uses these values:
header_pages:
  - index.md
  - about.md

# Minima theme specific settings
minima:
  #social_links:
    #twitter: your_twitter_username
    #github: your_github_username
    #linkedin: your_linkedin_username
    #instagram: your_instagram_username

# Permalinks
permalink: /:categories/:year/:month/:day/:title/

# Default values for YAML Front Matter
# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#     values:
#       layout: "post"
#       author: "Your Name"

# Author information
# author:
#   name: Your Name
#   email: youremail@example.com
#   twitter: your_twitter_username
#   github: your_github_username

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# SEO settings
seo:
  title: My Awesome Site
  description: A description of your site for SEO purposes.
  url: "https://yourusername.github.io"

# Custom 404 page
# This will use a 404.html page in your root directory if it exists.
